"""Batch D (2026-10): Cloudflare Workers AI free allocation, Mistral Le Chat free plan, self-hosted LibreTranslate (AGPL-3.0)."""

CF_SRC = "https://developers.cloudflare.com/workers-ai/platform/pricing/"
CF_TOOL = "Cloudflare Workers AI (free daily allocation)"
CF_FAMILY = "Cloudflare"
CF_FREE = "Free daily allocation of 10,000 Neurons; paid use only after upgrading to Workers Paid"
CF_LIMIT = "10,000 Neurons per day, reset at 00:00 UTC; requests fail once the day's allocation is used up"
MI_SRC = "https://mistral.ai/pricing/"
MI_TOOL = "Mistral Le Chat (Free plan)"
MI_FAMILY = "Mistral"
MI_FREE = "Free plan — no payment needed to start"
MI_LIMIT = "Limited messages, web searches, coding sessions and document uploads; exact allowances are shown in your account"
LT_SRC = "https://github.com/LibreTranslate/LibreTranslate"
LT_TOOL = "LibreTranslate (self-hosted, AGPL-3.0)"
LT_FAMILY = "Open Source (LibreTranslate)"
LT_FREE = "$0 to self-host — open-source under AGPL-3.0"
LT_LIMIT = "Your own server's capacity; no quota"

GUIDES = [
    {
        "slug": "cloudflare-workers-ai-daily-budget",
        "title": "Budget Your Free Daily Neurons on Cloudflare Workers AI",
        "hook": "Cloudflare gives everyone 10,000 free Neurons a day for Workers AI. Here is how to size a project so it never hits the wall, and how to tell when a model is too expensive.",
        "category": "business", "tool": CF_TOOL, "family": CF_FAMILY, "source": CF_SRC,
        "tags": ["cloudflare", "workers-ai", "budget", "api", "neurons"],
        "free": CF_FREE, "limits": CF_LIMIT,
        "intro": "Cloudflare's pricing page says Workers AI is included in both the free and paid Workers plans, with a free allocation of 10,000 Neurons per day, and that a day's limit is reset at 00:00 UTC. Neurons are a unit of GPU work that differs per model, so the first skill is reading the price table for the model you pick.",
        "steps": [
            ("Read the model's price in Neurons", "On the pricing page, each model lists Neurons per million input and output tokens. For example, the small <code>@cf/meta/llama-3.2-1b-instruct</code> lists 2,457 Neurons per million input tokens and 18,252 per million output tokens."),
            ("Do the sum for your workload", "Estimate tokens per request and requests per day. Roughly: 10,000 Neurons covers about 4 million input tokens on that small model, but only about half a million output tokens, because output costs more Neurons."),
            ("Pick the cheapest model that works", "Test two or three models on your real prompts and compare answer quality against the Neuron cost, not the headline price alone."),
            ("Cap your usage", "Add a counter in your Worker that stops calling the model at a daily threshold you set, and falls back to a message to the user."),
            ("Watch the dashboard", "Check the Workers AI usage view after the first week, then once a month."),
        ],
        "prompt": "For a Cloudflare Worker that calls a Workers AI model, outline: (1) the daily request budget from my 10,000-Neuron allocation given the model's Neuron price in my table, (2) a daily counter that stops calls at 90% of budget, (3) the message users see when the budget is reached. Show the calculation.\n\nMODEL PRICE TABLE:\n<paste>\nAVERAGE TOKENS PER REQUEST:\n<number>",
        "checks": ["The calculation uses the table for your exact model", "A daily stop is in place before you publish", "You know when the UTC day resets"],
        "pitfalls": ["Output tokens are the expensive part; ask for short answers.", "Some models are priced differently; read the entry for your model, not a neighbouring one."],
    },
    {
        "slug": "cloudflare-workers-ai-council-minutes-summary",
        "title": "Summarise Public Council Minutes into Plain English",
        "hook": "Turn long public meeting minutes into a one-page summary of what was decided, what it costs, and when you can have your say, using a small free AI endpoint.",
        "category": "civic", "tool": CF_TOOL, "family": CF_FAMILY, "source": CF_SRC,
        "tags": ["civic", "public-meetings", "summaries", "cloudflare", "plain-english"],
        "free": CF_FREE, "limits": CF_LIMIT,
        "intro": "Local government minutes are public but dense. A small Workers AI model can produce a neutral summary you can share with neighbours, as long as you keep the original minutes linked for accuracy.",
        "steps": [
            ("Get the minutes", "Download the official minutes as text or copy them from the council's website."),
            ("Chunk by agenda item", "Split long minutes by agenda item so each request stays small and within the daily budget."),
            ("Summarise each item", "Use the prompt below one item at a time."),
            ("Check against the source", "Verify every amount, date, and vote count against the minutes."),
            ("Publish with the link", "Always include the official source link beside the summary."),
        ],
        "prompt": "Summarise this agenda item from council minutes in plain English for a general reader. Give: what was proposed, what was decided, any cost or budget figures (quoted), the vote if recorded, and any next date for public comment. Under 120 words. Do not add opinions.\n\nMINUTES:\n<paste item>",
        "checks": ["Every figure matches the official minutes", "The vote and decision are quoted correctly", "The official link is on the summary"],
        "pitfalls": ["Minutes are not always the final word; check the approved version.", "A summary can omit important caveats. Recommend readers check the source."],
    },
    {
        "slug": "cloudflare-workers-ai-bill-sorter",
        "title": "Sort Your Household Bills into a Monthly Budget Sheet",
        "hook": "Paste a month of bill notices into a small, free AI endpoint and get a categorised budget table you can open in any spreadsheet.",
        "category": "household", "tool": CF_TOOL, "family": CF_FAMILY, "source": CF_SRC,
        "tags": ["budget", "bills", "spreadsheet", "cloudflare", "household"],
        "free": CF_FREE, "limits": CF_LIMIT,
        "intro": "Bills arrive in different formats from different companies. A short prompt can turn the text of those notices into one table, which is easier to compare month to month than your inbox.",
        "steps": [
            ("Collect the bill text", "Copy the amount, due date, and provider from each notice, one per paragraph. Remove account numbers first."),
            ("Run the sorter", "Use the prompt below in a small Worker or the Workers AI playground."),
            ("Verify the totals", "Add the amounts by hand and compare them with the total you expect."),
            ("Import to a spreadsheet", "Paste the CSV output into any spreadsheet app."),
            ("Compare month to month", "Keep one file per month and look for unexplained increases."),
        ],
        "prompt": "From the bill notices below, output CSV with the columns: provider, category (utilities, phone, internet, insurance, subscriptions, other), amount (number only), currency, due date (YYYY-MM-DD). Do not include account numbers. Output the header once, then one row per bill.\n\nNOTICES:\n<paste>",
        "checks": ["Totals match your manual sum", "No account numbers were sent to the model", "Due dates are correct"],
        "pitfalls": ["Remove account and card numbers before you paste anything.", "Subscriptions can hide in bank statements; the sorter only sees what you paste."],
    },
    {
        "slug": "mistral-le-chat-packing-list",
        "title": "Build a Packing List from a Forecast and Your Trip Plan",
        "hook": "Use Mistral's free Le Chat plan to turn your dates, destination, and planned activities into a packing list you can tick off, without a paid travel app.",
        "category": "travel", "tool": MI_TOOL, "family": MI_FAMILY, "source": MI_SRC,
        "tags": ["travel", "packing", "checklist", "mistral", "free-ai"],
        "free": MI_FREE, "limits": MI_LIMIT,
        "intro": "A good packing list depends on weather, activities, and how many days between washes. Le Chat's free plan is enough for a single careful planning session before a trip.",
        "steps": [
            ("Write the trip facts", "Dates, destination, transport, accommodation, and the activities you have booked."),
            ("Check the forecast yourself", "Look up the weather for those dates from a national weather service, and paste the summary."),
            ("Generate the list", "Use the prompt below. Ask for a list grouped into clothing, toiletries, documents, and tech."),
            ("Add personal items", "Medication, glasses, and dietary needs are yours to add; the model cannot know them."),
            ("Tick it off a week early", "Pack from the list and move unused items into a 'probably not needed' section for next time."),
        ],
        "prompt": "Create a packing checklist for this trip. Group items into clothing, toiletries, documents, electronics, and activity-specific gear. Base the clothing on this forecast summary. Add a note for each item that depends on the activity. Keep it under 80 items.\n\nTRIP:\n<dates, destination, transport, activities>\n\nFORECAST SUMMARY:\n<paste>",
        "checks": ["Documents such as passports and tickets are on the list", "Medication and prescriptions were added by you", "Clothing matches the forecast"],
        "pitfalls": ["Check entry rules, visas, and vaccination requirements with official government sources.", "Lists from a model can miss local rules; verify before you fly."],
    },
    {
        "slug": "mistral-le-chat-compare-job-offers",
        "title": "Compare Two Job Offers Side by Side",
        "hook": "Put two offers into one table covering pay, benefits, commute, and growth, then ask Le Chat to flag the trade-offs you might be missing.",
        "category": "career", "tool": MI_TOOL, "family": MI_FAMILY, "source": MI_SRC,
        "tags": ["job-offer", "career", "comparison", "mistral", "free-ai"],
        "free": MI_FREE, "limits": MI_LIMIT,
        "intro": "Offers differ in base pay, bonus, pension, holiday, and commute time. Writing them into one table makes the real comparison visible, and a free assistant can spot the line items that are easy to overlook.",
        "steps": [
            ("Write each offer in the same units", "Annual gross, bonus as a percentage, employer pension contribution, paid holiday days, and weekly commute time."),
            ("Add what matters to you", "Learning budget, flexibility, and team size can matter as much as pay."),
            ("Ask for the comparison", "Use the prompt below with both offers pasted in."),
            ("Check the numbers yourself", "Calculate the total compensation of each offer by hand, including the pension."),
            ("Ask the employers", "Write down questions for each employer, such as bonus history and how pension matching works."),
        ],
        "prompt": "Compare these two job offers in a table: base pay, bonus, pension, holiday, commute, and any other benefits. Then list the three biggest trade-offs and any items that are missing from one offer but included in the other. Do not recommend a choice; do not calculate tax.\n\nOFFER A:\n<paste>\n\nOFFER B:\n<paste>",
        "checks": ["Both offers use the same units", "Your own total compensation was checked by hand", "Questions for each employer are written down"],
        "pitfalls": ["Do not share another employer's confidential terms or your current employer's private data.", "Tax and pension rules differ by country; get advice from a qualified adviser for large decisions."],
    },
    {
        "slug": "mistral-le-chat-party-planner",
        "title": "Plan a Party Budget and Guest List with Le Chat",
        "hook": "Plan a birthday or celebration on a fixed budget: guest list, menu, and a cost sheet that tells you where the money goes before the invitations go out.",
        "category": "family", "tool": MI_TOOL, "family": MI_FAMILY, "source": MI_SRC,
        "tags": ["party", "budget", "family", "mistral", "planning"],
        "free": MI_FREE, "limits": MI_LIMIT,
        "intro": "Most party overspending happens in the food and drink line. Building the budget first, with a free model, makes it easy to see what you can afford before you commit.",
        "steps": [
            ("Set the total budget", "Decide the maximum you will spend, including decorations and a buffer of about ten percent."),
            ("List the guests and dietary needs", "Count adults and children, and note allergies."),
            ("Generate the plan", "Use the prompt below to get a menu, a shopping list, and a cost estimate per line."),
            ("Replace estimates with real prices", "Check two or three local shops and update the sheet."),
            ("Track as you go", "Log each purchase against the budget, and drop the least important line first if you run over."),
        ],
        "prompt": "Plan a party for {count} guests with a total budget of {budget}. Include: a simple menu that accommodates these dietary needs: {diet}, a shopping list grouped by shop section with estimated quantities, a cost estimate per line, and a total that stays within budget. Mark estimates clearly.",
        "checks": ["Dietary needs are covered by the menu", "The total is within your budget after real prices", "Each line is tracked as you spend"],
        "pitfalls": ["Food safety, especially for buffets and hot holding, needs proper guidance from a food-safety authority.", "Estimates are rough; replace them with real prices before you commit."],
    },
    {
        "slug": "mistral-le-chat-zine-outline",
        "title": "Plan a Small-Print Zine or Newsletter from a Content Outline",
        "hook": "Turn a pile of ideas into a page-by-page outline for a printed zine or community newsletter, with a layout plan you can draw by hand.",
        "category": "creative", "tool": MI_TOOL, "family": MI_FAMILY, "source": MI_SRC,
        "tags": ["zine", "creative", "layout", "mistral", "print"],
        "free": MI_FREE, "limits": MI_LIMIT,
        "intro": "A zine rewards planning. Folding an A4 sheet into eight pages forces you to choose what matters. A free model can help sort your ideas into a page sequence that works on paper.",
        "steps": [
            ("Dump your ideas", "Write every idea on a separate line, even weak ones."),
            ("Group them", "Ask for four to six themes, then choose the ones with the most material."),
            ("Generate the page plan", "Use the prompt below for an eight-page outline with a headline and one image idea per page."),
            ("Sketch the folds", "Draw the page plan on a folded sheet to check which pages face each other."),
            ("Print a test copy", "Print one copy and read it aloud before you make the run."),
        ],
        "prompt": "Create an eight-page outline for a printed A4 zine, folded into eight panels. For each page give: a headline, the main text in no more than 60 words, and one image or illustration idea. Put the cover on page 1 and the back cover on page 8. Use these themes: {themes}.",
        "checks": ["Page order makes sense when folded", "Images are yours or appropriately licensed", "A printed test copy was read aloud"],
        "pitfalls": ["Use only images you have rights to; check licences before you print.", "Keep personal details out of community publications unless the people have agreed."],
    },
    {
        "slug": "libretranslate-foreign-notices-selfhosted",
        "title": "Translate Foreign-Language Notices with Self-Hosted LibreTranslate",
        "hook": "Run an open-source translation service on your own machine to read signs, notices, and letters abroad, without sending the text to a commercial translator.",
        "category": "travel", "tool": LT_TOOL, "family": LT_FAMILY, "source": LT_SRC,
        "tags": ["translation", "travel", "self-hosted", "libretranslate", "open-source"],
        "free": LT_FREE, "limits": LT_LIMIT,
        "intro": "LibreTranslate is an open-source machine translation service you can self-host, and it has an HTTP API. It is a practical choice when you want translation without a commercial account. Quality is good for everyday phrases and weaker for legal or medical text.",
        "steps": [
            ("Install LibreTranslate", "Follow the installation options in the project's README (Python package or Docker). Choose only the languages you need."),
            ("Start the service", "Run it on your laptop and open the local web interface in your browser."),
            ("Translate short passages", "Paste one sentence or notice at a time and read the result against the original."),
            ("Confirm critical wording", "For anything with a deadline or a legal effect, ask a qualified translator or the issuing office."),
            ("Keep a phrase list", "Save useful translations as a list for your trip."),
        ],
        "prompt": "(Use the LibreTranslate interface or API.) Translate the notice below from {source} to {target}. Keep numbers, dates, and proper names unchanged, and flag any word that has more than one likely meaning.",
        "checks": ["Dates and numbers match the original", "Deadlines and legal wording were checked with a person", "Only the languages you need were installed"],
        "pitfalls": ["Machine translation can produce confident mistakes on medical or legal text.", "Check the AGPL-3.0 licence terms if you run a public service for other users."],
    },
    {
        "slug": "libretranslate-school-letters-selfhosted",
        "title": "Translate School Letters for Multilingual Families, Self-Hosted",
        "hook": "Help parents who read another language understand school letters on a service you run yourself, so family details stay on your own server.",
        "category": "family", "tool": LT_TOOL, "family": LT_FAMILY, "source": LT_SRC,
        "tags": ["school", "translation", "family", "libretranslate", "multilingual"],
        "free": LT_FREE, "limits": LT_LIMIT,
        "intro": "School letters carry dates, costs, and forms that matter. A self-hosted translator lets a volunteer or a parent translate them without uploading children's details to a commercial service.",
        "steps": [
            ("Set up the translator", "Install LibreTranslate on a home computer or small server, as described in the project README."),
            ("Translate paragraph by paragraph", "Long letters translate better in short chunks. Keep the original next to the translation."),
            ("Mark dates and amounts", "Circle every date, time, and amount on the original, then confirm them in the translation."),
            ("Ask the school for the official version", "For forms or consent slips, request the translated version from the school."),
            ("Share carefully", "Share the translation only with the family it concerns."),
        ],
        "prompt": "(Use the LibreTranslate interface or API.) Translate this school letter from {source} to {target}. Keep all dates, times, sums of money, names, and form numbers unchanged. Mark any sentence where the meaning is unclear.",
        "checks": ["Every date, time, and amount matches the original", "Consent or payment forms were confirmed with the school", "Translations are shared only with the relevant family"],
        "pitfalls": ["Do not rely on machine translation for consent, safeguarding, or medical letters.", "Children's details are sensitive; keep copies on the device you control."],
    },
    {
        "slug": "libretranslate-product-copy-selfhosted",
        "title": "Translate Product Descriptions into Three Languages for Free",
        "hook": "Localise a small online shop's product descriptions with a self-hosted, open-source translator, then polish the copy so it reads naturally in each language.",
        "category": "business", "tool": LT_TOOL, "family": LT_FAMILY, "source": LT_SRC,
        "tags": ["ecommerce", "translation", "localisation", "libretranslate", "small-business"],
        "free": LT_FREE, "limits": LT_LIMIT,
        "intro": "A small shop can reach new customers with translated product pages. A self-hosted translator gives you a first draft at no cost; a native speaker should still check the final copy before publishing.",
        "steps": [
            ("Write clear English copy", "Short sentences translate more reliably than long ones."),
            ("Translate description by description", "Paste one product at a time into LibreTranslate, once per target language."),
            ("Check product facts", "Verify sizes, materials, and care instructions against your supplier data."),
            ("Get a native check", "Ask a native speaker or a translator to review the top products first."),
            ("Keep a glossary", "Record your product names so they are translated the same way every time."),
        ],
        "prompt": "(Use the LibreTranslate interface or API.) Translate this product description from English to {target}. Keep product names, sizes, materials, and care instructions exactly as written.\n\nDESCRIPTION:\n<paste>",
        "checks": ["Sizes, materials and care instructions match your supplier data", "A native speaker reviewed the bestselling products", "Product names follow your glossary"],
        "pitfalls": ["Machine translation can make product claims stronger or weaker than you intended; check them.", "Consumer-law claims in each market differ; check local rules before you publish."],
    },
]
