"""Batch C (2026-10): Aider and Continue (both Apache-2.0) with local models; OpenRouter :free model variants."""

AIDER_SRC = "https://github.com/Aider-AI/aider"
AIDER_TOOL = "Aider (open-source coding agent, Apache-2.0)"
AIDER_FAMILY = "Open Source (Aider)"
CONT_SRC = "https://github.com/continuedev/continue"
CONT_TOOL = "Continue (open-source IDE assistant, Apache-2.0)"
CONT_FAMILY = "Open Source (Continue)"
OR_SRC = "https://openrouter.ai/docs/guides/routing/model-variants/free"
OR_TOOL = "OpenRouter :free model variants"
OR_FAMILY = "OpenRouter"
LOCAL_FREE = "$0 — open-source licence (Apache-2.0)"
LOCAL_LIMIT = "Your hardware is the limit when run with a local model"
OR_LIMIT = "Free variants have their own rate limits and availability; check the model page"

GUIDES = [
    {
        "slug": "aider-small-site-fixes-ollama",
        "title": "Maintain a Small Business Website with Aider and a Local Model",
        "hook": "Make small, reviewable edits to your business website from the terminal, using an open-source coding agent that talks to a model on your own machine.",
        "category": "business", "tool": AIDER_TOOL, "family": AIDER_FAMILY, "source": AIDER_SRC,
        "tags": ["website", "small-business", "aider", "ollama", "open-source"],
        "free": LOCAL_FREE, "limits": LOCAL_LIMIT,
        "intro": "Most small businesses change a price, a phone number, or an opening hour every few months, and pay someone to do it. Aider is an open-source terminal tool that edits files in a git repository and commits each change, so you can review and undo it.",
        "steps": [
            ("Put the site in git", "Make sure the website folder is a git repository, with a clean commit before you start."),
            ("Install Aider", "Follow the install instructions in the Aider repository. It is an open-source Python tool under Apache-2.0."),
            ("Point Aider at a local model", "Install Ollama and pull a coder model, then start Aider with an Ollama model string as shown in Aider's documentation for your version."),
            ("Ask for one small change", "Example: 'Change the opening hours in contact.html to Mon–Fri 9–5.' Ask for one change per run."),
            ("Review the diff before you push", "Run <code>git diff</code>, check the change, and only then publish the site."),
        ],
        "prompt": "Make only the change described below. Do not reformat other content, do not add new sections, and keep the existing HTML structure. After the change, list the files you touched.\n\nCHANGE:\n<describe one change>",
        "checks": ["The diff touches only the files you expected", "Prices, hours, and contact details match your source", "The site still loads locally before you publish"],
        "pitfalls": ["Local coder models are less capable than frontier models; keep changes small.", "Never let an agent run on a live server with no review step."],
    },
    {
        "slug": "continue-learn-codebase-ollama",
        "title": "Learn an Unfamiliar Codebase with Continue and a Local Model",
        "hook": "Use an open-source VS Code and JetBrains assistant, backed by a model on your laptop, to understand code you inherited without sending it to a cloud service.",
        "category": "learning", "tool": CONT_TOOL, "family": CONT_FAMILY, "source": CONT_SRC,
        "tags": ["coding", "learning", "continue", "ollama", "open-source"],
        "free": LOCAL_FREE, "limits": LOCAL_LIMIT,
        "intro": "Whether you are a new developer or a student, reading someone else's code is a skill. Continue is an open-source extension for VS Code and JetBrains. It can use a local model through Ollama, so your private code stays on your machine.",
        "steps": [
            ("Install Continue", "Install the Continue extension from your editor's marketplace; its repository is open source under Apache-2.0."),
            ("Connect a local model", "Pull a code model with Ollama, then add it in Continue's settings using the provider and model name shown in Continue's documentation."),
            ("Ask about one file at a time", "Select a function and ask for a plain-English walkthrough. Smaller selections give more accurate answers."),
            ("Trace one path", "Ask the model to follow a single request from the entry point to the database call, then verify each step yourself."),
            ("Write your own notes", "Keep a short architecture note in the repository and correct it as you learn."),
        ],
        "prompt": "Explain the selected code to someone who knows the language but not this project. Cover: what it does, its inputs and outputs, side effects, and any assumptions it makes. Point out anything that looks like a bug, but do not change the code.\n\nCODE:\n<selection>",
        "checks": ["Each explanation matches what you see when you step through it", "Suspected bugs are verified with a test, not accepted on trust", "Your notes are in your own words"],
        "pitfalls": ["Local models can misread complex control flow; confirm with a debugger.", "Do not paste secrets or credentials into any model, local or not."],
    },
    {
        "slug": "continue-local-pr-review",
        "title": "Review a Pull Request Locally Before You Merge It",
        "hook": "Get a second pair of eyes on your code changes with a free, open-source editor assistant and a model that stays on your computer.",
        "category": "business", "tool": CONT_TOOL, "family": CONT_FAMILY, "source": CONT_SRC,
        "tags": ["code-review", "pull-request", "continue", "ollama", "quality"],
        "free": LOCAL_FREE, "limits": LOCAL_LIMIT,
        "intro": "A solo developer or a two-person team often merges without review. A local model is not a replacement for a human reviewer, but it catches the obvious: unused variables, missing error handling, and tests that do not run.",
        "steps": [
            ("Check out the branch", "Use git to switch to the pull request's branch locally and view the diff."),
            ("Select the changed files", "Add only the changed files to the assistant's context so the review stays focused."),
            ("Run the review prompt", "Use the prompt below and ask for findings with file and line references."),
            ("Verify each finding", "Reproduce or reject every finding. Do not accept a suggestion you do not understand."),
            ("Run the tests", "Run the project's test suite and linter yourself; the model is not a test runner."),
        ],
        "prompt": "Review this diff as a careful senior engineer. List only concrete problems: bugs, missing error handling, unclear naming that affects behaviour, and missing tests. For each, give the file, the line, the problem, and a one-sentence fix. Say 'no issues found' if none.\n\nDIFF:\n<paste>",
        "checks": ["Every finding is reproduced or rejected", "Tests and linters were run by you", "No code was merged on the model's word alone"],
        "pitfalls": ["Models produce plausible but wrong findings; treat them as leads.", "Keep private repository code on local models, as the workflow above does."],
    },
    {
        "slug": "aider-unit-tests-small-script",
        "title": "Write Unit Tests for a Small Script with Aider",
        "hook": "Learn testing by having an open-source coding agent draft tests for your script, then reading every one to understand what it checks.",
        "category": "learning", "tool": AIDER_TOOL, "family": AIDER_FAMILY, "source": AIDER_SRC,
        "tags": ["testing", "python", "learning", "aider", "open-source"],
        "free": LOCAL_FREE, "limits": LOCAL_LIMIT,
        "intro": "Testing is easiest to learn from examples. Aider can draft tests for a small Python script; your job is to read them, run them, and make them fail on purpose once to prove they work.",
        "steps": [
            ("Start with a tiny script", "Pick a script under 100 lines, such as a unit converter or a budget calculator, and commit it."),
            ("Ask for tests", "Use the prompt below in Aider with the script added to the chat."),
            ("Run the tests", "Run <code>pytest</code> (install it first). Read the output even when everything passes."),
            ("Break the code on purpose", "Change one line of the script to produce a wrong answer and confirm a test fails."),
            ("Explain each test to yourself", "For each test, write one sentence saying what behaviour it protects."),
        ],
        "prompt": "Write pytest unit tests for the functions in this file. Cover normal inputs, edge cases such as zero and negative values, and one error case. Do not change the script. Keep each test short with a descriptive name.\n\nSCRIPT:\n<paste>",
        "checks": ["Tests run and pass on the correct code", "At least one test fails when you break the code on purpose", "You can explain each test"],
        "pitfalls": ["A passing test is not proof of correct behaviour if the test asserts the wrong thing.", "Do not accept generated tests that only call the function without checking the result."],
    },
    {
        "slug": "openrouter-free-model-comparison",
        "title": "Compare Three Free Models on OpenRouter Side by Side",
        "hook": "Use free model variants on OpenRouter to send the same prompt to several models and see which answer you actually prefer, at no cost.",
        "category": "learning", "tool": OR_TOOL, "family": OR_FAMILY, "source": OR_SRC,
        "tags": ["openrouter", "model-comparison", "free-ai", "learning"],
        "free": "$0 on :free variants — listed by OpenRouter as free versions of models", "limits": OR_LIMIT,
        "intro": "Model quality varies by task. OpenRouter lists some models with a :free suffix. Its documentation says these free variants may have different rate limits or availability than paid versions, so you should check the model page before relying on one.",
        "steps": [
            ("Create a free OpenRouter account", "Sign up and create an API key, or use the web chat interface if you prefer."),
            ("Find free variants", "Browse the models page and filter for models whose ID ends in <code>:free</code>. Note each model's context length."),
            ("Use the same prompt for all", "Paste one test prompt, identical for every model. Keep a copy of each answer."),
            ("Score blind", "Shuffle the answers, label them A, B, C, and rank them before you check which model is which."),
            ("Record the winner for each task type", "Keep a short table: task, best model, why. Re-check it in a month, since free availability changes."),
        ],
        "prompt": "Answer the question below in under 200 words. Be accurate, say so if you are unsure, and avoid filler.\n\nQUESTION:\n<your everyday question, e.g. 'How do I explain compound interest to a 12-year-old?'>",
        "checks": ["Each model ID you used ends in :free", "Same prompt, same settings for every model", "Rankings were made before you saw the model names"],
        "pitfalls": ["Free variants can be rate-limited at busy times; retry later rather than switching models.", "Do not send personal or confidential data to any cloud model without reading the provider's terms."],
    },
    {
        "slug": "openrouter-free-newsletter-drafts",
        "title": "Draft a Community Newsletter with a Free OpenRouter Model",
        "hook": "Write the monthly newsletter for a club, PTA, or small shop from a list of updates, using a free model variant and a reusable prompt.",
        "category": "business", "tool": OR_TOOL, "family": OR_FAMILY, "source": OR_SRC,
        "tags": ["newsletter", "community", "writing", "openrouter", "free-ai"],
        "free": "$0 on :free variants — listed by OpenRouter as free versions of models", "limits": OR_LIMIT,
        "intro": "Volunteer organisations publish a newsletter, and it takes an evening each month. A free model can turn a bullet list of updates into a readable draft, which you then edit for the community.",
        "steps": [
            ("Collect the updates", "Ask committee members to send three bullet points each by the same deadline."),
            ("Pick a free model", "Use a model ID ending in <code>:free</code> from the OpenRouter models page."),
            ("Generate the draft", "Use the prompt below. Ask for a subject line and two alternatives."),
            ("Edit for names and dates", "Check every name, date, and figure against the original bullets."),
            ("Save the prompt", "Keep the prompt in a text file so next month's issue has the same structure."),
        ],
        "prompt": "Write a community newsletter from the updates below. Use: a friendly subject line plus two alternatives, a 60-word opening, sections for each update with a heading, and a closing with the next meeting date. Use only facts in the updates. Keep it under 500 words.\n\nUPDATES:\n<paste>",
        "checks": ["Every date and name matches the bullets", "No fundraising or money figures were invented", "The subject line works without the body"],
        "pitfalls": ["Free models can change between sessions; keep your prompt stable so tone stays consistent.", "Email lists may have data rules; send only to people who subscribed."],
    },
    {
        "slug": "openrouter-free-language-practice",
        "title": "Practise a New Language with a Free OpenRouter Chat Model",
        "hook": "Hold daily conversation practice in a language you are learning, with a free model that corrects your mistakes gently and keeps a short vocabulary list.",
        "category": "travel", "tool": OR_TOOL, "family": OR_FAMILY, "source": OR_SRC,
        "tags": ["language-learning", "travel", "conversation", "openrouter", "free-ai"],
        "free": "$0 on :free variants — listed by OpenRouter as free versions of models", "limits": OR_LIMIT,
        "intro": "Before a trip, ten minutes of conversation a day beats a long weekly lesson. A model with a clear system prompt can act as a patient partner who corrects only the errors that matter.",
        "steps": [
            ("Choose a level and a topic", "For example: 'A3 level, ordering food and asking directions.'"),
            ("Set the role with a system prompt", "Use the prompt below so the model replies at your level and corrects only what matters."),
            ("Practise for ten minutes", "Write in the target language and try to answer without translating in your head."),
            ("Collect new words", "Ask for three new words from the conversation, with an example sentence each."),
            ("Review tomorrow", "Start the next session by asking the model to quiz you on yesterday's words."),
        ],
        "prompt": "You are a friendly conversation partner for a learner at {level} in {language}. Reply in {language} with one or two short sentences. After each reply, add a 'Correction' line in English only if there is a mistake that changes meaning. Keep a list of three new words at the end of each session.",
        "checks": ["Replies are at your level", "Corrections change meaning, not style", "Vocabulary is recorded in your own notes"],
        "pitfalls": ["Models can make grammar mistakes too; check any rule against a textbook or native speaker.", "Free variants can be slower at peak times; keep sessions short."],
    },
    {
        "slug": "openrouter-free-followup-notes",
        "title": "Draft Thank-You and Follow-Up Notes After Every Interview",
        "hook": "Send a specific, warm follow-up within a day of each interview, drafted with a free model from your own notes about what was discussed.",
        "category": "career", "tool": OR_TOOL, "family": OR_FAMILY, "source": OR_SRC,
        "tags": ["interview", "follow-up", "job-search", "openrouter", "free-ai"],
        "free": "$0 on :free variants — listed by OpenRouter as free versions of models", "limits": OR_LIMIT,
        "intro": "A specific follow-up that references something the interviewer said is remembered. You write the notes right after the call; a free model helps turn them into a short, polite message.",
        "steps": [
            ("Note three things right away", "Write the interviewer's name, one topic they cared about, and one question you want to answer better."),
            ("Generate a draft", "Use the prompt below with a model ID ending in <code>:free</code>."),
            ("Check the facts", "Confirm names, job title, and the date of the conversation."),
            ("Send within 24 hours", "Keep it to four or five sentences."),
            ("Track it", "Log the date and what you sent, so you can follow up once more after a week."),
        ],
        "prompt": "Write a follow-up email after a job interview. Keep it under 120 words. Thank the interviewer by name, mention the topic below in one sentence, add one useful point I want to add, and close politely without asking for an update. Do not invent details.\n\nNOTES:\n<paste>",
        "checks": ["Names and job title are correct", "The email references a real topic from the interview", "It was sent within one day"],
        "pitfalls": ["Do not paste other candidates' information or confidential company details into a model.", "Generic follow-ups are easy to spot; add one sentence in your own words."],
    },
    {
        "slug": "openrouter-free-naming-brainstorm",
        "title": "Brainstorm and Shortlist Names for a Side Project",
        "hook": "Generate forty name ideas for a project in a few minutes with a free model, then shortlist them with a checklist that catches the bad ones.",
        "category": "creative", "tool": OR_TOOL, "family": OR_FAMILY, "source": OR_SRC,
        "tags": ["naming", "brainstorm", "creative", "openrouter", "free-ai"],
        "free": "$0 on :free variants — listed by OpenRouter as free versions of models", "limits": OR_LIMIT,
        "intro": "Naming takes longer than building. A model is good at producing volume; your judgement is needed to pick the one that is easy to say, spell, search, and trademark-check.",
        "steps": [
            ("Describe the project in two sentences", "Say who it is for and what it does."),
            ("Generate a long list", "Use the prompt below to produce forty options across four styles."),
            ("Apply the checklist", "Remove names that are hard to spell, already used by a well-known product, or mean something unfortunate in another language."),
            ("Search for conflicts", "Check app stores, the company register in your country, and domain availability for each finalist. Trademark checks need a professional for anything serious."),
            ("Test aloud", "Say the final three names to a friend and ask which they remember."),
        ],
        "prompt": "Suggest 40 names for this project, in four groups of ten: descriptive, invented, metaphorical, and short (one or two syllables). Each name should be easy to spell and say. Output a simple numbered list with no explanations.\n\nPROJECT:\n<two sentences>",
        "checks": ["Final names pass a spelling and pronunciation test", "Each finalist was searched in app stores and company registers", "Trademark questions were referred to a professional"],
        "pitfalls": ["Models often suggest names already in use; always search.", "Naming is a judgement call; a shortlist of three is enough to decide."],
    },
]
