"""Batch A (2026-10): local guides built on Ollama (MIT-licensed, checked on GitHub 2026-10-08)."""

OLLAMA_SRC = "https://ollama.com"
OLLAMA_TOOL = "Ollama (local, MIT-licensed)"
OLLAMA_FAMILY = "Ollama / Self-Hosted Open Source"
LOCAL_FREE = "$0 — open-source (MIT licence)"
LOCAL_LIMIT = "Your own hardware is the only limit; no quota or account"

GUIDES = [
    {
        "slug": "ollama-lease-summary-offline",
        "title": "Summarise a Lease Offline with Ollama — Nothing Leaves Your Laptop",
        "hook": "Run a local model on your own computer to pull rent, notice periods, and repair duties out of a lease, without uploading the document anywhere.",
        "category": "civic", "tool": OLLAMA_TOOL, "family": OLLAMA_FAMILY, "source": OLLAMA_SRC,
        "tags": ["lease", "tenant-rights", "ollama", "offline", "privacy"],
        "free": LOCAL_FREE, "limits": LOCAL_LIMIT,
        "intro": "A lease holds your deposit, your notice period, and who fixes the boiler. Most people sign without reading it closely, and cloud chatbots ask you to upload personal documents. Ollama lets you do the reading on your own machine.",
        "steps": [
            ("Install Ollama", "Download the installer from ollama.com for macOS, Windows, or Linux and open a terminal. Check the install with <code>ollama --version</code>."),
            ("Download one small model", "Run <code>ollama pull llama3.2</code> (or another instruct model from the Ollama library that fits your RAM). The download happens once; afterwards the model runs offline."),
            ("Turn the lease into text", "Export the lease to a text file. If it is a scan, run it through the OCR guide in this directory first, then save the output as <code>lease.txt</code>."),
            ("Ask for a structured summary", "Use the prompt below, paste the lease text after it, and keep the answer in a file next to the lease."),
            ("Check every number against the source", "Open the original clause for each rent amount, date, and deadline. A small model can misread a clause; the page reference is what counts."),
        ],
        "prompt": "You are helping a tenant read a lease. Using only the text below, list: (1) monthly rent and due date, (2) deposit amount and conditions for return, (3) notice period for ending the tenancy, (4) who is responsible for repairs and by when, (5) any clause about fees, late payments, or entry. For each item give the section number or quote. If something is not stated, write 'not stated'. Do not give legal advice.\n\nLEASE TEXT:\n<paste here>",
        "checks": ["Every figure has a quoted clause or section number next to it", "Anything marked 'not stated' is double-checked in the original", "The lease file never left your computer"],
        "pitfalls": ["Long leases can exceed a small model's context window; split the document by section and summarise each part.", "A summary is not legal advice. For disputes, use the civic guides linked below."],
    },
    {
        "slug": "ollama-resume-tailor-offline",
        "title": "Tailor Your Resume Offline with a Local Model",
        "hook": "Match your existing resume to one job description on your own computer — no account, no upload, and no paid resume-builder subscription.",
        "category": "career", "tool": OLLAMA_TOOL, "family": OLLAMA_FAMILY, "source": OLLAMA_SRC,
        "tags": ["resume", "job-search", "ollama", "offline", "career"],
        "free": LOCAL_FREE, "limits": LOCAL_LIMIT,
        "intro": "Tailoring a resume to each posting is the most effective and most tedious part of a job search. You can do it privately: keep your resume and the job posting on your disk, and let a local model suggest edits you approve line by line.",
        "steps": [
            ("Save both documents as plain text", "Copy your resume and the job advert into <code>resume.txt</code> and <code>job.txt</code>. Plain text is easier for a small model than PDF."),
            ("Start a local model", "Run <code>ollama run llama3.2</code> and leave the chat open. Nothing you type is sent to a server."),
            ("Ask for matches, not rewrites", "Use the prompt below. You want a list of which of your existing bullets map to the job's requirements, and which requirements have no evidence."),
            ("Write the edits yourself", "Choose the bullets to keep, reword them in your own voice, and add numbers only if you can back them up."),
            ("Run a final consistency check", "Ask the model to flag dates, job titles, or claims that differ between the old and new versions."),
        ],
        "prompt": "Compare my resume and the job description below. Output three lists: (1) requirements my resume already evidences, quoting my bullet; (2) requirements with weak or no evidence; (3) my bullets that are not relevant to this role. Do not invent experience. Do not add numbers that are not in my resume.\n\nRESUME:\n<paste>\n\nJOB DESCRIPTION:\n<paste>",
        "checks": ["No claim appears that is absent from your original resume", "Dates and employer names match your source document", "You can defend every bullet in an interview"],
        "pitfalls": ["Local models sometimes invent metrics. If a number is not in your original, delete it.", "Pair this with the ATS and impact-statement guides in this directory for formatting."],
    },
    {
        "slug": "ollama-symptom-timeline-local",
        "title": "Turn a Symptom Diary into a Doctor-Ready Timeline, Locally",
        "hook": "Organise weeks of symptom notes into a dated timeline you can bring to an appointment, with the data never leaving your device.",
        "category": "health", "tool": OLLAMA_TOOL, "family": OLLAMA_FAMILY, "source": OLLAMA_SRC,
        "tags": ["health", "symptoms", "doctor-visit", "ollama", "privacy"],
        "free": LOCAL_FREE, "limits": LOCAL_LIMIT,
        "intro": "Health notes are some of the most sensitive data you own. This workflow turns a messy diary into a neutral timeline. It organises what you wrote; it does not diagnose anything, and your clinician makes every decision.",
        "steps": [
            ("Gather the raw notes", "Put each entry in a text file, one per line, starting with the date: <code>2026-09-14 headache after lunch, 6/10, ibuprofen helped</code>."),
            ("Run the model locally", "Use <code>ollama run llama3.2</code>. Keep the chat on your device; do not paste diary text into a cloud chatbot."),
            ("Ask for a neutral timeline", "Use the prompt below. You want dates, symptoms, severity, triggers you recorded, and what you tried."),
            ("Mark gaps", "Let the model list missing dates or missing severity scores so you can fill them in from memory before the visit."),
            ("Bring it to the appointment", "Print the timeline and add the questions you want answered. Keep your own original diary as the source of truth."),
        ],
        "prompt": "Turn the diary entries below into a chronological timeline. For each entry output: date, symptom(s), severity if recorded, possible triggers the writer noted, and treatments tried with the result. Do not interpret or diagnose. At the end, list dates with missing information and any questions a clinician might want answered, phrased neutrally.\n\nDIARY:\n<paste>",
        "checks": ["Every line matches an original diary entry", "No diagnosis or medication advice has been added", "Gaps are listed so you can fill them in"],
        "pitfalls": ["Do not use a summary in place of medical advice. Call your clinician or local emergency number for urgent symptoms.", "Small models can mislabel severity. Keep the numbers you wrote."],
    },
    {
        "slug": "ollama-recipe-box-local",
        "title": "Build a Searchable Local Recipe Box from Your Notes",
        "hook": "Turn scribbled recipe notes and family favourites into one clean, tagged cookbook on your own computer — a free, private alternative to recipe apps.",
        "category": "household", "tool": OLLAMA_TOOL, "family": OLLAMA_FAMILY, "source": OLLAMA_SRC,
        "tags": ["recipes", "cooking", "ollama", "offline", "household"],
        "free": LOCAL_FREE, "limits": LOCAL_LIMIT,
        "intro": "Recipes live in notebooks, screenshots, and texts from relatives. A local model can standardise them into one format you can search by ingredient, time, or dietary need.",
        "steps": [
            ("Collect the notes", "Put each recipe in its own text block, separated by a line of three dashes. Rough notes are fine."),
            ("Standardise the format", "Use the prompt below to get title, servings, ingredients with quantities, steps, and tags for each recipe."),
            ("Check quantities", "Compare the ingredient list against your original note. Models sometimes change a '1 tsp' into '1 tbsp'."),
            ("Save as Markdown", "Paste the output into <code>recipes.md</code>. Markdown opens in any editor and stays searchable forever."),
            ("Search with your file manager", "Search by ingredient with Ctrl+F or Cmd+F, or ask the model to filter tags for you."),
        ],
        "prompt": "Convert each recipe below into this Markdown format: '## Title', then 'Serves:', 'Time:', 'Ingredients' as a bullet list keeping the original quantities, 'Method' as numbered steps, and 'Tags' (e.g. vegetarian, quick, freezer-friendly). Do not add ingredients that are not in the original. Mark anything unclear with [check].\n\nRECIPES:\n<paste>",
        "checks": ["Every ingredient quantity matches the original note", "Unclear items are marked [check] and resolved", "The Markdown file is saved on your own device"],
        "pitfalls": ["Always taste-test a converted recipe before you trust a changed quantity.", "Food-safety guidance (cooking temperatures, storage) should come from a food-safety authority, not a model."],
    },
    {
        "slug": "ollama-family-chore-planner-offline",
        "title": "Plan Family Chores and Weekly Routines Offline",
        "hook": "Split household jobs fairly across the family with a local model that works from your own list, with no app accounts for the kids to sign up for.",
        "category": "family", "tool": OLLAMA_TOOL, "family": OLLAMA_FAMILY, "source": OLLAMA_SRC,
        "tags": ["chores", "family", "routines", "ollama", "offline"],
        "free": LOCAL_FREE, "limits": LOCAL_LIMIT,
        "intro": "A chore chart works best when everyone agrees to it. You can draft the fair split on your own computer, then let the family argue over the result, which is the point.",
        "steps": [
            ("List every recurring job", "Write each task with a rough time estimate: bins 5 min, dishes 15 min, hoovering 20 min, and so on."),
            ("Add constraints", "Note who is away on which days, sports practices, and any tasks someone dislikes or cannot do."),
            ("Ask for a draft rota", "Use the prompt below. Ask for two options, each with a weekly table, so the family can compare."),
            ("Review as a family", "Read both drafts at dinner. Swap tasks by hand; do not regenerate until you have agreed on the shape."),
            ("Save and reuse", "Keep the chosen rota as <code>chores.md</code> and update it monthly."),
        ],
        "prompt": "Create two weekly chore rotas for a household with the members and tasks below. Keep total time per person within 20% of each other, respect the availability notes, and never give a task to someone listed as unable to do it. Output a table per option: day, task, person, minutes.\n\nMEMBERS AND AVAILABILITY:\n<paste>\n\nTASKS WITH MINUTES:\n<paste>",
        "checks": ["Time per person is roughly balanced", "No one is assigned a task they cannot do", "Two options were compared before choosing"],
        "pitfalls": ["Estimates are guesses. Adjust after two weeks of real use.", "Keep rewards and allowances as a family decision; a model should not set them."],
    },
    {
        "slug": "ollama-client-email-drafts-offline",
        "title": "Write Client Emails from Bullet Notes, Fully Offline",
        "hook": "Turn your meeting bullet points into polished follow-up emails on your own machine, so client details never reach a third-party server.",
        "category": "business", "tool": OLLAMA_TOOL, "family": OLLAMA_FAMILY, "source": OLLAMA_SRC,
        "tags": ["email", "client-work", "small-business", "ollama", "offline"],
        "free": LOCAL_FREE, "limits": LOCAL_LIMIT,
        "intro": "Freelancers and small firms write the same follow-up email dozens of times a month. Keeping those drafts local protects client confidentiality, which many contracts require.",
        "steps": [
            ("Write bullets straight after the call", "Three to six lines: what was agreed, who does what, and the next date."),
            ("Generate a draft", "Use the prompt below with your house style: greeting, short paragraphs, one clear ask."),
            ("Strip anything you would not send", "Delete internal notes, prices you did not agree, and names of other clients."),
            ("Edit the tone yourself", "Read it aloud once. Small models can sound stiff or overly apologetic."),
            ("Keep a template library", "Save the best outputs as templates in a local folder for next time."),
        ],
        "prompt": "Write a short follow-up email to a client. Use a warm, direct tone, no more than 150 words, and a single clear call to action. Include only the facts below; do not add prices, dates, or commitments that are not listed.\n\nBULLET NOTES:\n<paste>",
        "checks": ["Every commitment and date matches your notes", "No internal or other-client information appears", "The email has one clear next step"],
        "pitfalls": ["Read contracts before promising timelines; the model cannot know your obligations.", "Local speed depends on your hardware. A smaller model is quicker for short emails."],
    },
    {
        "slug": "ollama-weekly-meal-prep-local",
        "title": "Plan Weekly Meal Prep with a Local Model and a Shopping List",
        "hook": "Build a balanced week of batch-cooked meals and a shopping list from what you already have, using a free model that runs on your laptop.",
        "category": "health", "tool": OLLAMA_TOOL, "family": OLLAMA_FAMILY, "source": OLLAMA_SRC,
        "tags": ["meal-prep", "nutrition", "shopping-list", "ollama", "budget"],
        "free": LOCAL_FREE, "limits": LOCAL_LIMIT,
        "intro": "Meal prep saves money and decisions. A local model can plan around what you own and the diet you follow, without storing your food habits in a cloud account.",
        "steps": [
            ("Inventory the cupboard", "List what you already have, with rough quantities, in a text file."),
            ("Set your constraints", "Note servings, budget, allergies, and foods you will not eat."),
            ("Generate a plan", "Use the prompt below for five dinners and two lunches, reusing ingredients across meals."),
            ("Build the shopping list", "Ask for a list grouped by store section, subtracting what you already own."),
            ("Check the food-safety basics", "Confirm storage times and reheating guidance with a food-safety authority before batch-cooking."),
        ],
        "prompt": "Plan seven dinners and seven lunches for batch cooking. Reuse ingredients across meals to reduce waste. Respect these constraints: servings, allergies, and foods to avoid below. Output: the plan by day, a shopping list grouped by store section with only items I do not already have, and the cooking order for one prep session.\n\nINVENTORY:\n<paste>\n\nCONSTRAINTS:\n<paste>",
        "checks": ["No listed allergen or excluded food appears", "The shopping list subtracts your inventory", "Storage and reheating times were checked against a food-safety source"],
        "pitfalls": ["Nutrition numbers from a model are estimates. For medical diets, ask a dietitian or your clinician.", "Cooked food has safe storage limits; do not rely on a model for them."],
    },
    {
        "slug": "ollama-textbook-flashcards-local",
        "title": "Turn a Textbook Chapter into Flashcards with Local Ollama",
        "hook": "Convert a chapter you have already photographed or exported into spaced-repetition cards on your own computer — no study app subscription needed.",
        "category": "learning", "tool": OLLAMA_TOOL, "family": OLLAMA_FAMILY, "source": OLLAMA_SRC,
        "tags": ["flashcards", "study", "spaced-repetition", "ollama", "offline"],
        "free": LOCAL_FREE, "limits": LOCAL_LIMIT,
        "intro": "Flashcards work because you retrieve the answer yourself. A local model can draft the question-and-answer pairs from your own chapter; you check each one before you study it.",
        "steps": [
            ("Export the chapter text", "Copy the text into <code>chapter.txt</code>, or OCR the pages first with the Tesseract guide in this directory."),
            ("Ask for question-answer pairs", "Use the prompt below. Keep chunks to one or two sections so the model stays accurate."),
            ("Check each card against the book", "Verify every answer on the page. Delete cards that test trivia rather than understanding."),
            ("Import into your flashcard app", "Export as a CSV with two columns, front and back, and import it into any spaced-repetition tool that accepts CSV."),
            ("Review daily for ten minutes", "Short, frequent sessions beat long cramming sessions."),
        ],
        "prompt": "From the chapter text below, write 15 flashcards that test understanding, not trivia. Format each as: FRONT ; BACK, one per line, with the back under 25 words. Use only information in the text. Skip any section that is only examples or exercises.\n\nTEXT:\n<paste>",
        "checks": ["Each answer can be found in the source text", "Cards test explanations and relationships, not isolated dates", "The CSV imports cleanly"],
        "pitfalls": ["Models sometimes write confident wrong answers. Treat the draft as a first pass.", "Copyright: keep flashcards for your own study, not for publication."],
    },
]
